// services/JournalentryService.js
import axios from "@utils/axios";

// Get all journal entries with optional filters
export const getJournalEntries = async (params = {}) => {
  try {
    const response = await axios.get('/journal-entries', { params });
    return response.data;
  } catch (error) {
    console.error("Error fetching journal entries:", error);
    throw error;
  }
};

// Get single journal entry by ID
export const getJournalEntry = async (id) => {
  try {
    const response = await axios.get(`/journal-entries/${id}`);
    return response.data;
  } catch (error) {
    console.error("Error fetching journal entry:", error);
    throw error;
  }
};

// Create new journal entry
export const createJournalEntry = async (data) => {
  try {
    // Entry number is auto-generated by backend, no need to include it
    const response = await axios.post('/journal-entries', data);
    return response.data;
  } catch (error) {
    console.error("Error creating journal entry:", error);
    throw error;
  }
};

// Update journal entry
export const updateJournalEntry = async (id, data) => {
  try {
    const response = await axios.put(`/journal-entries/${id}`, data);
    return response.data;
  } catch (error) {
    console.error("Error updating journal entry:", error);
    throw error;
  }
};

// Delete journal entry (soft delete)
export const deleteJournalEntry = async (id) => {
  try {
    const response = await axios.delete(`/journal-entries/${id}`);
    return response.data;
  } catch (error) {
    console.error("Error deleting journal entry:", error);
    throw error;
  }
};

// Search journal entries
export const searchJournalEntries = async (searchTerm, filters = {}) => {
  try {
    const response = await axios.get('/journal-entries', {
      params: {
        search: searchTerm,
        ...filters
      }
    });
    return response.data;
  } catch (error) {
    console.error("Error searching journal entries:", error);
    throw error;
  }
};

// Get journal entries by status
export const getJournalEntriesByStatus = async (status) => {
  try {
    const response = await axios.get('/journal-entries', {
      params: { status }
    });
    return response.data;
  } catch (error) {
    console.error("Error fetching journal entries by status:", error);
    throw error;
  }
};

// Get next entry number
export const getNextEntryNumber = async () => {
  try {
    const response = await axios.get('/journal-entries-next-number');
    return response.data;
  } catch (error) {
    console.error("Error fetching next entry number:", error);
    throw error;
  }
};
