// src/config/permissions.js
export const permissions = {
  admin: {
    chatbot: { view: true },
    dashboard: { view: true, edit: true },
    hrMaster: { view: true },
    show: { view: true, edit: true },
    employeeMaster: { view: true, edit: true, delete: true },
    departmentMaster: { view: true, edit: true },
    shiftTime: { view: true, edit: true },
    grouproster: { view: true, edit: true },
    resignation: { view: true, edit: true },
    termination: { view: true, edit: true },
    userManagement: { view: true, edit: true, delete: true },
    allowanceDeduction: { view: true },
    createNewAllowance: { view: true, edit: true },
    createNewDeduction: { view: true, edit: true },
    loans: { view: true },
    viewLoans: { view: true, edit: true },
    employeeLoan: { view: true, edit: true },
    salaryProcess: { view: true },
    SalaryProcessPage: { view: true, edit: true },
    SalaryPage: { view: true },
    timeAttendance: { view: true },
    TimeCard: { view: true, edit: true },
    Overtime: { view: true, edit: true },
    leaveMaster: { view: true, edit: true },
    leaveApproval: { view: true, approve: true },
    hrLeaveApproval: { view: true, approve: true },
    noPayManagement: { view: true, edit: true },
    leavecalendar: { view: true },
    reports: { view: true },
    utilities: { view: true },
    pms: { view: true },
    pmsDashboard: { view: true },
    performanceReviews: { view: true, edit: true },
    kpis: { view: true, edit: true },
    taskApproval: { view: true, approve: true },
    myKPIs: { view: true },
    employeeEvaluation: { view: true, edit: true },
    lms: { view: true },
    lmsDashboard: { view: true },
    manageExams: { view: true, edit: true },
    manageCourses: { view: true, edit: true },
    myProgress: { view: true },
    lmsUserStats: { view: true },
    
    customer: { view: true, edit: true },
    center: { view: true, edit: true },
    
    createUtilityBill: { view: true, edit: true },
    utilityBillPayment: { view: true, edit: true },
    
    salesOrder: { view: true, edit: true },
    salesReturn: { view: true, edit: true },
    grn: { view: true, edit: true },
    purchaseReturn: { view: true, edit: true },
    purchaseOrder: { view: true, edit: true },
    stockTransfer: { view: true, edit: true },
    stockVerification: { view: true, edit: true },
    
    invoices: { view: true, edit: true },
    expenses: { view: true, edit: true },
    
    accountingSettings: { view: true, edit: true },
    usersAndRoles: { view: true, edit: true },
    PerformanceAppraisal: { view: true, edit: true },
    doubleEntry: { view: true, edit: true },
    supplier: { view: true, edit: true },
    product: { view: true, edit: true },
    inventory: { view: true, edit: true },
    productList: { view: true, edit: true },
    discountLevel: { view: true, edit: true },
    productType: { view: true, edit: true },
    pendingApprovals: { view: true, edit: true },
    // Administration - Only admin can manage permissions
    permissionManagement: { view: true, edit: true },
    roleManagement: { view: true, edit: true },
    userManagement: { view: true, edit: true, delete: true, create: true },
  },
  hr: {
    chatbot: { view: true },
    dashboard: { view: true, edit: true },
    hrMaster: { view: true },
    show: { view: true, edit: true },
    employeeMaster: { view: true, edit: true, delete: true },
    departmentMaster: { view: true, edit: true },
    shiftTime: { view: true, edit: true },
    grouproster: { view: true, edit: true },
    resignation: { view: true, edit: true },
    termination: { view: true, edit: true },
    userManagement: { view: true, edit: true, delete: true },
    allowanceDeduction: { view: true },
    createNewAllowance: { view: true, edit: true },
    createNewDeduction: { view: true, edit: true },
    loans: { view: true },
    viewLoans: { view: true, edit: true },
    employeeLoan: { view: true, edit: true },
    salaryProcess: { view: true },
    SalaryProcessPage: { view: true, edit: true },
    SalaryPage: { view: true },
    timeAttendance: { view: true },
    TimeCard: { view: true, edit: true },
    Overtime: { view: true, edit: true },
    leaveMaster: { view: true, edit: true },
    leaveApproval: { view: true, approve: true },
    hrLeaveApproval: { view: true, approve: true },
    noPayManagement: { view: true, edit: true },
    leavecalendar: { view: true },
    reports: { view: true },
    utilities: { view: true },
    pms: { view: true },
    pmsDashboard: { view: true },
    performanceReviews: { view: true, edit: true },
    kpis: { view: true, edit: true },
    taskApproval: { view: true, approve: true },
    myKPIs: { view: true },
    employeeEvaluation: { view: true, edit: true },
    lms: { view: true },
    lmsDashboard: { view: true },
    manageExams: { view: true, edit: true },
    manageCourses: { view: true, edit: true },
    myProgress: { view: true },
    lmsUserStats: { view: true },
    
    salesOrder: { view: true, edit: true },
    salesReturn: { view: true, edit: true },
    grn: { view: true, edit: true },
    purchaseReturn: { view: true, edit: true },
    purchaseOrder: { view: true, edit: true },
    stockTransfer: { view: true, edit: true },
    stockVerification: { view: true, edit: true },
    
    invoices: { view: true, edit: true },
    expenses: { view: true, edit: true },
    
    accountingSettings: { view: true, edit: true },
    usersAndRoles: { view: true, edit: true },
    PerformanceAppraisal: { view: true, edit: true },
    inventory: { view: true, edit: true },
    masterFiles: { view: true, edit: true },
    productList: { view: true, edit: true },
    discountLevel: { view: true, edit: true },
  },
  supervisor: {
    chatbot: { view: true },
    dashboard: { view: true },
    hrMaster: { view: true },
    show: { view: true },
    employeeMaster: { view: true },
    departmentMaster: { view: true },
    leaveApproval: { view: true, approve: true },
    hrLeaveApproval: { view: true, approve: true },
    leaveMaster: { view: true },
    leavecalendar: { view: true },
    reports: { view: true },
    pms: { view: true },
    pmsDashboard: { view: true },
    performanceReviews: { view: true, edit: true },
    kpis: { view: true, edit: true },
    myKPIs: { view: true },
    lms: { view: true },
    lmsDashboard: { view: true },
    manageExams: { view: true, edit: true },
    manageCourses: { view: true, edit: true },
    myProgress: { view: true },
    lmsUserStats: { view: true },
    
    customer: { view: true, edit: true },
    center: { view: true, edit: true },
  product: { view: true, edit: true },
    
 
    
    salesOrder: { view: true, edit: true },
    salesReturn: { view: true, edit: true },
    grn: { view: true, edit: true },
    purchaseReturn: { view: true, edit: true },
    purchaseOrder: { view: true, edit: true },
    stockTransfer: { view: true, edit: true },
    stockVerification: { view: true, edit: true },
    
    invoices: { view: true },
    expenses: { view: true },
    
    inventory: { view: true, edit: true },
  },
  user: {
    chatbot: { view: true },
    dashboard: { view: true },
    hrMaster: { view: true },
    show: { view: true },
    leaveMaster: { view: true, edit: true },
    leavecalendar: { view: true },
    myKPIs: { view: true },
    lms: { view: true },
    lmsDashboard: { view: true },
    manageCourses: { view: true },
    manageExams: { view: true },
    myProgress: { view: true },
    
    pms: { view: true },
    pmsDashboard: { view: true },
    performanceReviews: { view: true, edit: true },
    
    inventory: { view: true },
    product: { view: true },
  },
  employee: {
    chatbot: { view: true },
    dashboard: { view: true },
    hrMaster: { view: true },
    show: { view: true },
    leaveMaster: { view: true, edit: true },
    leavecalendar: { view: true },
    myKPIs: { view: true },
    lms: { view: true },
    lmsDashboard: { view: true },
    manageCourses: { view: true },
    manageExams: { view: true },
    myProgress: { view: true },
    
    pms: { view: true },
    pmsDashboard: { view: true },
    performanceReviews: { view: true, edit: true },
   
    inventory: { view: true },
    product: { view: true },
  },
};
