export const banks = [
  "Alliance Finance Company PLC",
  "Amana Bank PLC",
  "Axis Bank",
  "Bank of Ceylon",
  "Cargills Bank Limited",
  "Central Bank of Sri Lanka",
  "Central Finance PLC",
  "Citizen Development Business Finance PLC",
  "Citi Bank",
  "Commercial Bank PLC",
  "Commercial Credit & Finance PLC",
  "Commercial Leasing and Finance",
  "Deutsche Bank",
  "DFCC Bank PLC",
  "Habib Bank Ltd",
  "Hatton National Bank PLC",
  "HDFC Bank",
  "HNB Grameen Finance Limited",
  "Hongkong Shanghai Bank",
  "ICICI Bank Ltd",
  "Indian Bank",
  "Indian Overseas Bank",
  "Kanrich Finance Limited",
  "LB Finance PLC",
  "LOLC Finance PLC",
  "MCB Bank Ltd",
  "Merchant Bank of Sri Lanka & Finance PLC",
  "Mercantile Investment and Finance PLC",
  "National Development Bank PLC",
  "National Savings Bank",
  "Nations Trust Bank PLC",
  "Pan Asia Banking Corporation PLC",
  "Peoples Bank",
  "People's Leasing & Finance PLC",
  "Public Bank",
  "Regional Development Bank",
  "Sampath Bank PLC",
  "Sanasa Development Bank",
  "Senkadagala Finance PLC",
  "Seylan Bank PLC",
  "Standard Chartered Bank",
  "State Bank of India",
  "State Mortgage & Investment Bank",
  "Union Bank of Colombo PLC",
  "Vallibel Finance PLC",
];

// sort alphabetically (case-insensitive)
banks.sort((a, b) => a.localeCompare(b));
